### PR TITLE
Build fat binary with arm64 and x86_64

### PR DESCRIPTION
**Pull request by plubius**
Add native Mac Silicon support so that Rosetta 2 does not need to be installed.

### CODE REVIEW

**Comment by rodyager** [comment]
Working on Version 2 at the moment which includes support for both architectures and some other improvements.

Rod

On 21 Jun 2022, at 9:30 am, PL ***@***.******@***.***>> wrote:


Add native Mac Silicon support so that Rosetta 2 does not need to be installed.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/rodyager/RWTS-PDFwriter/pull/20

Commit Summary

  *   bc51d83<https://github.com/rodyager/RWTS-PDFwriter/pull/20/commits/bc51d831d8487248bd25cf6414beb5184b49443b> Build fat binary with arm64 and x86_64

File Changes

(1 file<https://github.com/rodyager/RWTS-PDFwriter/pull/20/files>)

  *   M sources/buildscript.sh<https://github.com/rodyager/RWTS-PDFwriter/pull/20/files#diff-1b41b37c69136423db54771b879c2d47bd54c02d6a97267a8e78309339badeec> (2)

Patch Links:

  *   https://github.com/rodyager/RWTS-PDFwriter/pull/20.patch
  *   https://github.com/rodyager/RWTS-PDFwriter/pull/20.diff

**Comment by plubius** [comment]
No worries. You can close this pull request. Are you interested in notarizing your .app and .pkg and bundling them into a .dmg for version 2? If yes, let me know and I can create a pull request with our notarization and .dmg packaging shell commands for your build script.

**Comment by rodyager** [comment]
The new version will be accompanied by a notarized installer which installs both the printer driver and the utility app (and opens the app on installation to prompt the installing user to create the location at which their print outputs will appear.)

Rod

On 21 Jun 2022, at 9:53 am, PL ***@***.******@***.***>> wrote:



No worries. You can close this pull request. Are you interested in notarizing your .app and .pkg and bundling them into a .dmg for version 2? If yes, let me know and I can create a pull request with our notarization and .dmg packaging shell commands for your build script.

**Comment by plubius** [comment]
Closing this pull request as my patch is obsolete now that v2.0 has been released. Thank you for all your work!

**Pull request closed without merging**
